config/routes.rb
Rails.application.routes.draw do

  #root url
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new'
  post '/sessions/create', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  # OmniAuth routes
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # users routes (nested events and tasks)
  resources :users, except: [:destroy] do
    resources :events, only: [:index, :new, :edit, :show] do #might night even need this
      resources :tasks, only: [:index, :edit, :show] #might not even need this
    end
    member do
      get 'profile'
    end
  end

  delete '/users/:id', to: 'users#destroy', as:'delete_user'

  # nested routes (events) --- do I need this is I have the above? Test out later
  resources :events, except: [:destroy] do
    resources :tasks, only: [:new, :create, :show]
    member do
      get 'show_admin'
    end
  end

  # event routes
  delete '/events/:id', to: 'events#destroy'

  # Not sure how to setup this route with the alias issue. This might be correct. I will see.
  resources :tasks, only: [:index, :edit, :show, :update, :destroy]

  # user_task (participation)
  resources :users_tasks, only: [:create, :destroy] do
    collection do
      patch :user_complete
      patch :admin_complete
    end
  end

  # friendship controlle action routes
  resources :friendships, only: [:create, :destroy]

  # I don't think I am going to use this.
  # But, I might need it if I decide to do use activerecord associations to deal with this
  resources :usersevents, only: [:destroy]
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :event
  has_many :user_tasks, dependent: :destroy
  has_many :users, through: :user_tasks

  validates_presence_of :name, message: "The task name cannot be blank"
  validates_uniqueness_of :name, case_sensitive: false, scope: :event_id, message: "You already have a task with that name in this event."
  validate :deadline_date_cannot_be_in_the_past
  validates :users, length: {
    maximum: :max_participants,
    message: "The task can have only #{:max_participants} number of participants."
  }

  before_validation :set_defaults
  before_create :capitalize_name
  after_create :assign_admin

  scope :group_tasks, -> { where(group_task: true) }
  scope :solo_tasks, -> { where(group_task: false) }
  scope :not_complete, -> { where("admin_confirmed_completion_at IS NULL") }
  scope :admin_marked_complete, -> { where("admin_confirmed_completion_at IS NOT NULL") }

  ####################################################
  # Adds: conditions for validation & custom message #
  # Makes sure that the date has not already passed  #
  ####################################################
  def deadline_date_cannot_be_in_the_past
    errors.add(:deadline_date, "The deadline date cannot be in the past!") if
      deadline_date and deadline_date < Date.today
  end

  ######################
  # Capitalizes the Name #
  ######################
  def capitalize_name
    self.name = self.name.capitalize
  end

  ##################################################################
  # sets the max_participants for a solo_task to 1                 #
  # even if a user manages to insert a different value             #
  # into the field for number of max people allowed to participate #
  ##################################################################
  def set_defaults
    unless self.group_task
      self.max_participants = 1
    end
  end

  #############################################
  # Assigns the admin to be same as the event #
  #############################################

  def assign_admin
    event = Event.find(self.event_id)
    self.admin_id = event.admin_id
    self.save
  end

  ###########################
  # Checks if user id admin #
  ###########################
  def task_admin(user)
    self.admin_id == user.id
  end

  #################################
  # Checks if user already exists #
  #################################
  def detect_user?(participant)
    self.users.where(id: participant.id).first
  end

  #########################
  # Adds a user to a task #
  #########################
  def add_participant(participant)
    event = Event.find(self.event_id)

    if self.task_type == "Group Task" # || (self.task_type == "Solo Task" && self.users.size != 1)
      self.users << participant
    elsif self.task_type == "Solo Task" && self.users.size != 1
      self.users << participant
    end

    participant.events << event unless participant.event_ids.include?(event_id)

    self.save
    participant.save
  end

  ##############################
  # Removes a user from a task #
  ##############################
  def remove_participant(participant)
    user_task = UserTask.find_by_user_id_and_task_id(participant.id, self.id)
    user_task.delete if user_task

    event = Event.find(self.event_id)
    event.remove_from_event(participant)
  end

  ##########################################################
  # Lists the usernames of users participating in the task #
  ##########################################################
  def list_participants
    list = self.users
    if list.size == 1
      list.first.username
    else
      list.map { |u| u.username.capitalize }.join(", ")
    end
  end

  ######################
  # Labels a task type #
  ######################
  def task_type
    self.group_task ? "Group Task" : "Solo Task"
  end

  ########################################################################################
  # determines how many points each user should get                                      #
  # I am choosing this method of point distribution to make it fair                      #
  # if a single user completes a group task, why shouldn't that person earn more points? #
  ########################################################################################
  def points_distributed_to_each_participant
    points = (self.points_awarded.to_f / self.users.size).round(3)
  end

  ##############################################################
  # handles the distribution of the points to each participant #
  ##############################################################
  def distribute_points
    self.users.each do |user|
      total_points = user.total_points.to_f + points_distributed_to_each_participant.to_f
      total_points = total_points.round(4)
      user.total_points = total_points
      user.save(validate: false)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_not_logged_in, except: [:new, :create]
  before_action :prevent_double_login
  before_action :user_exists?, except: [:index, :new, :create, :destroy]
  before_action :set_user, except: [:index, :new, :create, :destroy]

  def index
    @users = User.all.order(:username)
    respond_to do |format|
      format.html { render :index }
      format.json { render json: { current_user: current_user.as_json(only: [:id, :username]), users: @users.as_json(only: [:id, :username]) } }
    end
  end

  def new
    @user = User.new
  end

  ##########################################
  # Handles the Logic for Account Creation #
  ##########################################
  def create
    @user = User.new(user_params)

    # If it passes validations, creates the account, logs in the user, and flashes a success message.
    # Otherwise, it stores the validation error messages to display them in the view.
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You have successfully registered!"
      redirect_to user_path(@user)
    else
      flash[:warnings] = []
      @user.errors.messages.each { |error| flash[:warnings] << error.second.first }
      redirect_to new_user_path
    end
  end

  #################################################
  # handles routing to the user's account details #
  #################################################
  def profile
    respond_to do |format|
      format.html { render :profile }
      format.json { render json: @user }
    end
  end

  ###########################################
  # handles routing to the user's show page #
  ###########################################
  def show
    @friends_events = Event.not_admin(@user)
    @adminned_events = Event.admin(@user)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @user }
    end
  end

  ###################################################
  # handles routing to the user's account edit page #
  ###################################################
  def edit
    respond_to do |format|
      format.html { render :edit }
      format.json { render json: @user.to_json(only: [:email, :username, :first_name, :last_name, :address, :telephone_num]) }
    end
  end

  #######################################
  # handles updating the user's account #
  #######################################
  def update
    @user.update(user_params.except(:email))
    if @user.errors.any?
      flash[:warnings] = []
      @user.errors.messages.each { |error| flash[:warnings] << error.second.first }
    else
      flash[:success] = "Successfully updated details" unless @user.errors.any?
    end
    redirect_to edit_user_path(@user)
  end

  #####################################
  # handles deleting a user's account #
  #####################################
  def destroy
    User.destroy(current_user.id)
    redirect_to root_path
    flash[:warnings] = [ "You deleted your account." ]
  end

  private

    ###########################
    # finds and sets the user #
    ###########################
    def set_user
      @user = User.find_by(id: params[:id])
    end

    ##########################################
    # Deals with the issue of orphaned users #
    ##########################################
    def user_exists?
      unless set_user
        redirect_to users_path
        flash[:warnings] = [ "That user does not exist" ]
      end
    end

    #############################################
    # A listing of the params permitted for use #
    #############################################
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :telephone_num,
        :address,
        :email,
        :username,
        :password
      )
    end

end

app/helpers/users_helper.rb
module UsersHelper
  ### FINISHED EDITING ###

  #############################################################
  # Displays a friend link                                    #
  # links to the create action in the friendships controller  #
  #############################################################
  def add_friend_link(user)
    if user != current_user
      ("<span>" + (button_tag "Add Friend", class: "btn btn-info btn-xs index-add-friend-button", data: { crnt_user_id: "#{current_user.id}", friend_id: "#{user.id}" }) + "</span>").html_safe
    end
  end

  #############################################################
  # Displays an unfriend link                                 #
  # links to the destroy action in the friendships controller #
  #############################################################
  def unfriend_link(friendship)
    (link_to "Unfriend", friendship_path(friendship), method: :delete,
    data: { confirm: "Are you sure you want to unfriend this person?" }, class: yield)
  end

  ###########################################
  # Displays an add or remove friend button #
  ###########################################
  def add_remove_friend_button(user)
    if user.id != current_user.id
      friendship = friends?(user)
      friendship ? unfriend_link(friendship) { "btn-sm btn-danger" } : add_friend_link(user) { "btn btn-info" }
    end
  end

  ############################################################
  # conditional logic for displaying a friends dropdown menu #
  ############################################################
  def friends_dropdown(user)
    if user == current_user || friends?(user)
      yield
    end
  end

  #########################################
  # Links to Users and allows to unfriend #
  #########################################

  def link_to_user(user)
    (link_to user.username, user_path(user)) + (user == current_user ? "" : " <::> ") +
    (friends?(user) ? "<span>Your Friend</span>".html_safe : add_friend_link(user) { "" })
  end

  #####################################
  # Links to User on Users Index Page #
  #####################################

  def friends_page(friendship, user)
    if friendship.friend_id == user.id
      (link_to friendship.user.username, user_path(friendship.user))
    else
      (link_to friendship.friend.username, user_path(friendship.friend))
    end
  end

  ################################################################################
  # Displays the name and link to a friend's homepage                            #
  # If user page is current user's homepage, then provides an option to unfriend #
  ################################################################################
  def link_to_friend(friendship, user)
    if user == current_user
      friends_page(friendship, user) + " - ( " + unfriend_link(friendship) { "" } + " ) "
    else
      friends_page(friendship, user)
    end
  end

  #############################################
  # Links to the task and corresponding event #
  # that the user is taking part in           #
  #############################################
  def task_participating_in(task, user)
    (link_to task.name, event_task_path(task.event_id, task)) + ", in Event: " +
    (link_to Event.find(task.event_id).name, user_event_path(user, task.event_id)) + ", by: " +
    (link_to User.find(task.admin_id).username, user_path(task.admin_id))
  end

  #############################################
  # Links to the task and corresponding event #
  # that the user is taking part in           #
  #############################################
  def friend_event_participating_in(event, user)
    (link_to event.name, user_event_path(event.admin_id, event)) + ", by:" +
    (link_to User.find(event.admin_id).username, user_event_path(event.admin_id, event))
  end


  ##########################
  # Incomplete Group Tasks #
  ##########################
  def users_incomplete_group_tasks
    @user.tasks.group_tasks.not_complete
  end

  #########################
  # Incomplete Solo Tasks #
  #########################
  def users_incomplete_solo_tasks
    @user.tasks.solo_tasks.not_complete
  end

end

app/views/users/_adminned_events_card.html.erb
<div class="col">
  <div class="card mb-4 border border-info">
    <div class="card-header bg-info text-white">
      <div id="adminned-events-title"></div>
    </div>
    <ul id="adminned-events-list" class="list-group list-group-flush">
    </ul>
  </div>
</div>

app/views/users/_card.html.erb
<div class="col friends-only" style="display: none">
  <div class="card mb-4 border border-info">
    <div class="card-header bg-info text-white">
      <%= yield %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit Account Info</h1>

<label>Email: <%= @user.email %></label>
<br>
<br>
<%= form_for @user do |f| %>

  <%= f.label :username, "Display Name: " %>
  <%= f.text_field :username %>
  <br>
  <br>
  <%= f.label :first_name, "First Name: " %>
  <%= f.text_field :first_name %>
  <br>
  <br>
  <%= f.label :last_name, "Last Name: " %>
  <%= f.text_field :last_name %>
  <br>
  <br>
  <%= f.label :address, "Address: " %>
  <%= f.text_field :address %>
  <br>
  <br>
  <%= f.label :telephone_num, "Telephone: " %>
  <%= f.text_field :telephone_num %>
  <br>
  <br>

  <%= f.submit "Update Account Details", data: { confirm: "Are you sure you want to submit these changes?" }, class: "btn btn-info" %>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<div id='users'>
</div>

<ol>
  <% @users.each do |user| %>
    <li id="user-<%= user.id %>">
      <%= link_to_user(user) %>
    </li>
  <% end %>
</ol>

app/views/users/new.html.erb
<h1>Create a New Account</h1>

<br>

<%= form_for @user do |f| %>

  <div class="container">
    <%= f.label :username, "Display Name: " %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email, "Email: " %>
    <%= f.email_field :email %>
    <br>
    <br>
    <%= f.label :password, "Password: " %>
    <%= f.password_field :password %>
    <br>
    <br>
  </div>

  <%= f.submit "Create Account", class: "bg-info text-white" %>

<% end %>

app/views/users/profile.html.erb
<h1 class="main-header"><%= "#{@user.username}'s Profile" %></h1>

<br>
<br>
<p>Display Name: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>
<p>Password: <%= link_to "Change Password", edit_user_path(@user),  class: "btn-sm btn-info" %></p>
<p>-------------------------------------------</p>
<p>Name: <%= @user.full_name %></p>
<p>Address: <%= @user.address %></p>
<p>Telephone: <%= @user.telephone_num %></p>


<br>
<br>
<%= link_to "Edit Details", edit_user_path(@user), class: "btn btn-info" %>
<%= link_to "Delete Account", @user, method: :delete, data: { confirm: "Are you sure you want to delete your account?" }, class: "btn btn-danger" %>

app/views/users/show.html.erb
<h1 id="user-homepage-header" class="main-header"></h1>
<br>
<h3 id="users-total-points"></h3>

<br>
<br>

<div class="container">
  <div class="row">


      <!-- Events the User Created -->
      <%= render partial: "adminned_events_card", locals: { adminned_events: @adminned_events, user: @user } %>

      <!--Solo Tasks the User is Participating in -->
      <%= render layout: "card" do %>
        <div id="solo-tasks-title"></div>
      </div>
        <ul id="solo-tasks-list" class="list-group list-group-flush"></ul>
      <% end %>

      <div class="w-100"></div>

      <!-- Events that the User's friends created and that the user is participating in -->
      <%= render layout: "card" do %>
        <div id="friend-events-title"></div>
      </div>
      <ul id="friends-events-list" class="list-group list-group-flush">
        <% @friends_events.with_tasks.each do |event| %>
          <% if event.user_ids.include?(@user.id) %>
            <li class="list-group-item">
              <%= friend_event_participating_in(event, @user) %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <% end %>

      <!-- List the Group Tasks the User is Participating in -->
      <%= render layout: "card" do %>
        <div id="group-tasks-title"></div>
      </div>
      <ul id="group-tasks-list" class="list-group list-group-flush"></ul>
      <% end %>


  </div>

    <br>
    <br>

  <!-- when visiting a user's homepage: -->
  <!-- if it is the current user's page or the current user is friends with the user page's owner -->
  <div class="btn-group">
    <button id='friends-list-button' type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
    <div id="scrollable-friends-list" class="dropdown-menu scrollable-menu"></div>
  </div>

  <br>
  <br>

  <!-- An add/remove friend link on a different user's page -->
  <!-- is this necessary? -->
  <div id="friend-unfriend-button">
  </div>

</div>