config/routes.rb
Rails.application.routes.draw do

  #root url
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new'
  post '/sessions/create', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  # OmniAuth routes
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # users routes (nested events and tasks)
  resources :users, except: [:destroy] do
    resources :events, only: [:index, :new, :edit, :show] do #might night even need this
      resources :tasks, only: [:index, :edit, :show] #might not even need this
    end
    member do
      get 'profile'
    end
  end

  delete '/users/:id', to: 'users#destroy', as:'delete_user'

  # nested routes (events) --- do I need this is I have the above? Test out later
  resources :events, except: [:destroy] do
    resources :tasks, only: [:new, :create, :show]
    member do
      get 'show_admin'
    end
  end

  # event routes
  delete '/events/:id', to: 'events#destroy'

  # Not sure how to setup this route with the alias issue. This might be correct. I will see.
  resources :tasks, only: [:index, :edit, :show, :update, :destroy]

  # user_task (participation)
  resources :users_tasks, only: [:create, :destroy] do
    collection do
      patch :user_complete
      patch :admin_complete
    end
  end

  # friendship controlle action routes
  resources :friendships, only: [:create, :destroy]

  # I don't think I am going to use this.
  # But, I might need it if I decide to do use activerecord associations to deal with this
  resources :usersevents, only: [:destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :user_events, dependent: :destroy
  has_many :users, through: :user_events

  validate :deadline_date_cannot_be_in_the_past

  validates_presence_of :name, message: "You must provide a name for this event."
  validates_uniqueness_of :name, case_sensitive: false, scope: :admin_id, message: "You already have an event with that name."

  before_create :capitalize_name
  after_create :set_admin_user

  scope :set_order, -> { order("tasks.group_task DESC, tasks.name ASC, tasks.max_participants ASC") }
  scope :admin, -> (user){ where(admin_id: user.id) }
  scope :not_admin, -> (user){ where.not(admin_id: user.id) }
  scope :with_tasks, -> { where(id: Task.not_complete.pluck(:event_id)) }

  ####################################################
  # Adds: conditions for validation & custom message #
  # Makes sure that the date has not already passed  #
  ####################################################
  def deadline_date_cannot_be_in_the_past
    errors.add(:deadline_date, "The deadline date cannot be in the past!") if
      deadline_date and deadline_date < Date.today
  end

  #####################################################################
  # Sets the default order of the tasks by                            #
  # task type, then marked for completion or not, and lastly, by name #
  #####################################################################
  def order_tasks
    self.tasks.order("group_task ASC, user_completed_at ASC, name ASC")
  end

  ######################
  # Capitalizes the Name #
  ######################
  def capitalize_name
    self.name = self.name.capitalize
  end

  ################################################
  # Adds this event to an admin user's event_ids #
  ################################################
  def set_admin_user
    u = User.find(self.admin_id)
    u.event_ids << self.id
    u.events << self
    u.save
  end

  #####################################################################
  # Checks if a particular user is participating in the event's tasks #
  #####################################################################
  def tasks_with_user(user)
    task_ids = []
    self.tasks.each do |task|
      if task.user_ids.include?(user.id)
        task_ids << task.id
      end
    end

    task_ids
  end

  ##############################################
  # deletes a user's association with an event #
  ##############################################

  def remove_from_event(participant)
    if self.tasks_with_user(participant).empty?
      user_event = UserEvent.find_by_user_id_and_event_id(participant.id, self.id)
      self.user_ids.delete(participant.id)
      user_event.delete
    end
  end

  private

    #################################################
    # Development method: deletes all orphan events #
    #################################################

    def self.end_all_invalid_events

      range = (1..17).to_a

      range.each do |n|
        u ||= User.find_by(id: n)
        unless u
          self.where(admin_id: n).each { |e| e.destroy }
        end
      end
    end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :event_exists?, only: [:show, :edit, :update, :destroy, :show_admin]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :show_admin]

  ###########################################
  # handles routing to a list of all events #
  ###########################################
  def index
    @events = Event.all.order(:name)
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @events }
    end
  end

  ##############################################
  # handles routing to form to create an event #
  ##############################################
  def new
    @event = Event.new
  end

  ####################################
  # handles the creation of an event #
  ####################################
  def create
    @event = Event.new(event_params)
    @event.admin_id = current_user.id

    if @event.save
      redirect_to show_admin_event_path(@event)
    else
      flash[:warnings] = []
      @event.errors.messages.each { |error| flash[:warnings] << error.second.first }
      redirect_to new_event_path
    end
  end

  ###########################################
  # handles routing to an event's show page #
  ###########################################
  def show
    @incomplete_ordered_tasks = @event.order_tasks.not_complete
    @complete_ordered_tasks = @event.order_tasks.admin_marked_complete
    @task = Task.new
    @admin = User.find(@event.admin_id)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @event }
    end
  end

  ############################################
  # handles routing to form to edit an event #
  ############################################
  def edit
  end

  #############################
  # handles updating an event #
  #############################
  def update
    @event.update(event_params)
    redirect_to show_admin_event_path(@event)
  end

  #############################
  # handles deleting an event #
  #############################
  def destroy
    @event_name = @event.name
    Event.destroy(@event.id)
    redirect_to user_path(current_user)
    flash[:warnings] = [ "You deleted the event: #{@event_name}." ]
  end

  ############################################
  # handles routing to the admin's show page #
  ############################################
  def show_admin
    @admin = User.find(@event.admin_id)

    if @event.admin_id != current_user.id
      redirect_to event_path(@event)
      flash[:warnings] = [ "Hey, stop it! You aren't this event's admin!" ]
    else
      @incomplete_ordered_tasks = @event.order_tasks.not_complete
      @complete_ordered_tasks = @event.order_tasks.admin_marked_complete
      @task = Task.new
      respond_to do |format|
        format.html { render :show_admin }
        format.json { render json: @event }
      end
    end
  end


  private

    ############################
    # finds and sets the event #
    ############################
    def set_event
      @event = Event.find_by(id: params[:id])
    end

    ####################################################
    # avoids running into the issue of orphaned events #
    ####################################################
    def event_exists?
      unless set_event
        redirect_to events_path
        flash[:warnings] = [ "That event does not exist" ]
      end
    end

    #############################################
    # A listing of the params permitted for use #
    #############################################
    def event_params
      params.require(:event).permit(
        :name,
        :deadline_date,
        :deadline_time,
        :admin_id
      )
    end

end

app/helpers/events_helper.rb
module EventsHelper

  ### FINISHED EDITING ###

  ###########################################################
  # Determines if the current_user is an admin of the event #
  ###########################################################
  def user_is_event_admin(event)
    event.admin_id == current_user.id
  end

  ####################################################################################
  # Displays a checkbox or appropriate message depending on a task's complete status #
  ####################################################################################
  def display_user_checkbox(task)
    if task.admin_confirmed_completion_at
      "Complete"
      task.completed = true
      task.save
    elsif task.user_completed_at && !task.admin_confirmed_completion_at
      "Pending Confirmation"
    elsif task.user_ids.include?(current_user.id)
      check_box_tag "user_task_ids[]", task.id
    end
  end

  #####################################
  # Displays checkboxes for the admin #
  #####################################
  def display_admin_checkbox(task)
    check_box_tag "admin_task_ids[]", task.id
  end

  ###################################################
  # Checks if the visiting user is the task's admin #
  ###################################################
  def is_admin_user?(task)
    task.admin_id == current_user.id
  end

  ####################################################
  # Determines if the visting user can join the task #
  ####################################################
  def permission_to_join?(task)
    if friends?(task.admin_id) || is_admin_user?(task)
      yield
    else
      "Cannot Join"
    end
  end


  #########################################################
  # Determines if a user if participating in an event     #
  # Displays 'Join Task' or 'Leave Task' link accordingly #
  #########################################################
  def check_task_availability(task)
    unless  task.completed
      if task.user_ids.include?(current_user.id)
        if task.users.size <= task.max_participants
          link_to "Leave Task", users_task_path(task), method: :delete, data: { confirm: "Are you sure you wish to leave task: #{task.name}?"}
        end

      elsif task.users.size < task.max_participants
        unless task.user_completed_at
          if task.user_ids.exclude?(current_user.id)
            link_to "Join Task", users_tasks_path(task, id: task.id), method: :post
          end
        end

      else
        "Task Full"
      end
    end
  end

end

app/views/events/_completed_tasks.html.erb
<h2>COMPLETED TASKS</h2>

<p>Sort by: Name | Task Type | Points Awarded | Max Participants | Join Status </p>

<div class="table-responsive">
  <table class="table border border-info">
    <thead class="thead bg-info text-white">
      <%= render partial: 'table_headers', locals: { event_instance: event } %>
    </thead>

    <tbody>
      <% completed_tasks.each do |task| %>
        <tr>
          <%= render partial: 'table_rows', locals: { event_instance: event, task_instance: task } %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label :name, "Event Name: " %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :deadline_date, "Event Deadline (Date): " %>
  <%= f.date_field :deadline_date %>
  <br>
  <%= f.label :deadline_time, "Event Deadline (Time)" %>
  <%= f.time_field :deadline_time %>
  <br>
  <%= f.hidden_field :admin_id %>
  <br>

  <%= f.submit submit_msg, data: { confirm: confirm_msg }, class: "btn bg-info text-white" %>
<% end %>

app/views/events/_show_heading.html.erb
<div>
  <div class="align-top clearfix">
    <h1 class="main-header float-left"><%= event.name %></h1>
    <h2 class="sub-header float-right">Event's Admin: <%= link_to admin.username, user_path(admin) %></h2>
  </div>

  <div>
    <h6 class="sub-header">Due Date & Time</h6>
    <h6>Date: <%= event.deadline_date.strftime("%m-%d-%y") if event.deadline_date %></h6>
    <h6>Time: <%= event.deadline_time.strftime("%I:%M %p") if event.deadline_time %></h6>
  </div>
</div>

<br>
<br>
<br>

app/views/events/_table_headers.html.erb
<th scope="col" class="col-auto">Task Name</th>
<th scope="col" class="col-auto">Task Type</th>
<th scope="col" class="col-auto">Points Awarded</th>
<th scope="col" class="col-auto">Max Participants</th>
<th scope="col" class="col-auto">Due Date</th>
<th scope="col" class="col-auto">Participants</th>
<th scope="col" class="col-auto">Join Status</th>
<th scope="col" class="col-auto">Completion Status</th>

app/views/events/_table_rows.html.erb
<td id='task-link'><%= link_to task_instance.name, event_task_path(task_instance.event_id, task_instance) %></td>
<td id='task-type'><%= task_instance.task_type %></td>
<td id='task-points-awarded'><%= task_instance.points_awarded %></td>
<td id='task-max-participants'><%= task_instance.max_participants %></td>
<td id='task-instance-deadline-date'><%= task_instance.deadline_date.strftime("%m-%d-%y") if task_instance.deadline_date %></td>
<td id='task-participant-list'><%= task_instance.list_participants %></td>
<td><%= permission_to_join?(task_instance) { (check_task_availability task_instance) } %></td>
<td><%= permission_to_join?(task_instance) { (display_user_checkbox task_instance) } %></td>


<%= form_for task_instance do |f| %>
  <%= f.hidden_field :event_id, value: task_instance.event_id %>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event: <%= @event.name %></h1>

<%= render partial: 'form', locals: { submit_msg: "Update Event", confirm_msg: "Are you sure you want to submit these changes?" } %>

<br>

<%= link_to "Delete Event", @event, method: :delete, data: { confirm: "Are you sure you want to delete this event?" }, class: "btn-sm bg-danger text-white" %>

app/views/events/index.html.erb
<h1>Index of Events</h1>

<br />

<h5>Sort By:</h5>
<button id="sort-events-ascending" type="button" class="btn btn-sm btn-outline-primary">Title Ascending</button>
<button id="sort-events-descending" type="button" class="btn btn-sm btn-outline-primary">Title Descending</button>

<br />
<br />

<div id="all-events">
  <ol>
  </ol>
</div>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render partial: 'form', locals: { submit_msg: "Create Event", confirm_msg: "Finish creating this event?" } %>

app/views/events/show.html.erb
<%= render partial: 'show_heading', locals: { event: @event, admin: @admin } %>

<h2>INCOMPLETE TASKS</h2>

<br />

<div id="task-sorting-buttons">
  <strong>Sort By:</strong>
  <button id="non-admin-sort-tasks-name" type="button" class="btn btn-xs btn-outline-primary">Name</button>
  <button id="non-admin-sort-tasks-task-type" type="button" class="btn btn-xs btn-outline-primary">Type</button>
  <button id="non-admin-sort-tasks-points-awarded" type="button" class="btn btn-xs btn-outline-primary">Points Awarded</button>
  <button id="non-admin-sort-tasks-max-participants" type="button" class="btn btn-xs btn-outline-primary">Max Participants</button>
  <button id="non-admin-sort-tasks-join-status" type="button" class="btn btn-xs btn-outline-primary">Join Status</button>
</div>

<br />

<div class="table-responsive dark">
  <%= form_tag user_complete_users_tasks_path, method: :patch do %>
    <table class="table border border-info">
      <thead class="thead bg-info text-white">
        <tr>
          <%= render partial: 'table_headers', locals: { event_instance: @event } %>
        </tr>
      </thead>

      <tbody>
        <% @incomplete_ordered_tasks.each do |task| %>
          <tr>
            <%= render partial: 'table_rows', locals: { event_instance: @event, task_instance: task } %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= submit_tag "Mark as Complete", class: "btn btn-info" %>
    <% if user_is_event_admin(@event) %>
      <%= link_to "View as Admin", show_admin_event_path(@event), class: "btn btn-outline-primary" %>
    <% end %>
  <% end %>
</div>

<br>
<br>
<br>

<!-- Completed Tasks -->
<%= render partial: 'completed_tasks', locals: { completed_tasks: @complete_ordered_tasks, event: @event } %>

app/views/events/show_admin.html.erb
<%= render partial: 'show_heading', locals: { event: @event, admin: @admin } %>

<h1>ADMIN PAGE</h1>
<br>
<h2>INCOMPLETE TASKS</h2>

<br />

<div id="task-sorting-buttons">
  <strong>Sort By:</strong>
  <button id="admin-sort-tasks-name" type="button" class="btn btn-xs btn-outline-primary">Name</button>
  <button id="admin-sort-tasks-task-type" type="button" class="btn btn-xs btn-outline-primary">Type</button>
  <button id="admin-sort-tasks-points-awarded" type="button" class="btn btn-xs btn-outline-primary">Points Awarded</button>
  <button id="admin-sort-tasks-max-participants" type="button" class="btn btn-xs btn-outline-primary">Max Participants</button>
  <button id="admin-sort-tasks-join-status" type="button" class="btn btn-xs btn-outline-primary">Join Status</button>
</div>

<br />

<div class="table-responsive">
  <%= form_tag admin_complete_users_tasks_path, method: :patch do %>
    <table class="table border border-info">
      <thead class="thead bg-info text-white">
        <tr>
          <%= render partial: 'table_headers', locals: { event_instance: @event } %>
          <th scope="col">Confirm Task Completion?</th>
          <th scope="col">Delete?</th>
        </tr>
      </thead>

      <tbody id='incomplete_tasks_list'>
        <% @incomplete_ordered_tasks.not_complete.each do |task| %>
          <tr>
            <%= render partial: 'table_rows', locals: { event_instance: @event, task_instance: task } %>
            <td><%= display_admin_checkbox task %></td>
            <td><%= link_to "Delete Task", task_path(task), method: :delete, data: { confirm: "Are you sure you want to delete this task?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= submit_tag "Confirm Task Completion", class: "btn btn-info" %>
    <%= link_to "View as Non-Admin", event_path(@event), class: "btn btn-outline-primary" %>
  <% end %>
</div>


<br>
<br>
<br>

<%= render partial: 'completed_tasks', locals: { completed_tasks: @complete_ordered_tasks, event: @event } %>


<br>
<br>
<br>


<% if @event.admin_id == current_user.id %>
  <h1>Create a New Task</h1>

  <div id="create_event_task">
    <%= form_for [@event, @task] do |f| %>

      <%= render partial: "tasks/form", locals: { f: f } %>
      <%= f.submit "Create Task", class: "btn btn-info" %>

    <% end %>
  </div>

  <br>
  <%= link_to "Edit Event Details", edit_event_path, class: "btn btn-outline-primary" %>
<% end %>