config/routes.rb
Rails.application.routes.draw do

  #root url
  root 'static_pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new'
  post '/sessions/create', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  # OmniAuth routes
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # users routes (nested events and tasks)
  resources :users, except: [:destroy] do
    resources :events, only: [:index, :new, :edit, :show] do #might night even need this
      resources :tasks, only: [:index, :edit, :show] #might not even need this
    end
    member do
      get 'profile'
    end
  end

  delete '/users/:id', to: 'users#destroy', as:'delete_user'

  # nested routes (events) --- do I need this is I have the above? Test out later
  resources :events, except: [:destroy] do
    resources :tasks, only: [:new, :create, :show]
    member do
      get 'show_admin'
    end
  end

  # event routes
  delete '/events/:id', to: 'events#destroy'

  # Not sure how to setup this route with the alias issue. This might be correct. I will see.
  resources :tasks, only: [:index, :edit, :show, :update, :destroy]

  # user_task (participation)
  resources :users_tasks, only: [:create, :destroy] do
    collection do
      patch :user_complete
      patch :admin_complete
    end
  end

  # friendship controlle action routes
  resources :friendships, only: [:create, :destroy]

  # I don't think I am going to use this.
  # But, I might need it if I decide to do use activerecord associations to deal with this
  resources :usersevents, only: [:destroy]
end

app/views/layouts/application.html.erb
<!Doctype html>

<html lang="en">
  <head>
    <title>AAM ETM: Event Task Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>


  <body class="<%= controller_name %> <%= action_name %>">
    <div class="container-fluid background">
      <div class="container ">

        <div class="navbar-container">
          <nav class="navbar navbar-expand-lg navbar-light rounded border border-info">
            <a class="navbar-brand" href="<%= root_path %>">AAM.ETM</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">

                <!---------------->
                <!--------------->
                <!-- LOGGED IN -->
                <!--------------->
                <!---------------->
                <% if logged_in? %>

                  <!-- User's Homepage -->
                  <li class="nav-item active">
                    <a class="nav-link" href="<%= user_path(current_user) %>"><%= "#{current_user.username}" %></a>
                  </li>

                  <!-- INDEX of USERS -->
                  <li class="nav-item">
                    <a class="nav-link" href="<%= users_path %>">All Users<span class="sr-only">(current)</span></a>
                  </li>

                  <!-- DROP-DOWN: EVENTS -->
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Event Options
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="<%= events_path %>">All Events</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="<%= new_user_event_path(current_user) %>">Create New Event</a>
                    </div>
                  </li>

                  <!-- DROP-DOWN: TASKS -->
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Task Options
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="<%= tasks_path %>">All Tasks</a>
                    </div>
                  </li>

                  <!-- DROP-DOWN: User's Account -->
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Your Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="<%= profile_user_path(current_user) %>">Profile</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="<%= signout_path %>" rel="nofollow" data-method="delete">Log Out</a>
                    </div>
                  </li>
                </ul>

                <!-- SEARCH FORM -->
                <form class="form-inline my-2 my-lg-0">
                  <label style="margin-right: 50px;">Your Total Points: <%= current_user.display_points %></label>
                </form>
              <% else %>
                <!------------------->
                <!------------------->
                <!-- NOT Logged in -->
                <!------------------->
                <!------------------->

                <!-- WELCOME PAGE -->
                <li class="nav-item active">
                  <a class="nav-link" href="<%= root_path %>">Welcome to ETM<span class="sr-only">(current)</span></a>
                </li>

                <!-- SIGN-UP Page -->
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Sign Up Options
                  </a>

                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<%= new_user_path %>">Create a New Account</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/auth/facebook">Sign Up using Facebook</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/auth/github">Sign Up using Github</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/auth/google_oauth2">Sign Up using Google</a>
                  </div>
                  </li>

                <!-- LOG-IN Options -->
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Log In Options
                  </a>

                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="<%= login_path %>">Log into Your Account</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/auth/facebook">Log in using Facebook</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/auth/github">Log in using Github</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/auth/google_oauth2">Log in using Google</a>
                  </div>
                </li>
              <% end %>
            </div>
          </nav>
        </div> <!-- navbar-container -->

        <div class="spacer"></div>

        <div class = "container main-content bg-white text-dark border border-info" >

          <%= render partial: 'flash_messages/flash' %>
          <div id="flash-success-danger-message"></div>

          <%= yield %>

          <br>
          <br>

          <% unless request.path == '/' %>

            <div class="back-button">
              <%= link_to "Return to the Previous Page", :back, class: "btn btn-outline-primary" %>
            </div>

          <% end %>


          <div class="large-spacer"></div>

          <!-- Footer Columns -->

          <div class="container footer-columns">
            <div class="row page-links">
              <div class="col-sm-4">

                <!-- Contact info -->
                <h3>Contact</h3>

                <address>
                  <p>Address:</p>
                  AAM . ETM<br>
                  P.O. Box 77777<br>
                  Brooklyn, NY 11223
                </address>
                <p>
                  Email: <a href="mailto:info@aametm.com">info@aametm.com</a><br>
                  Phone: +1 (762) 798-7700
                </p>
              </div>

              <!-- Useful links -->
              <div class="col-sm-4">
                <h3>Links</h3>
                <p>
                  <a href="#" target="_blank">Something Useful 1</a><br>
                  <a href="#" target="_blank">Something Useful 2</a><br>
                  <a href="#" target="_blank">Something Useful 3</a>
                </p>
              </div>

              <!-- Social Media Links -->
              <div class="col-sm-4">
                <h3>Follow</h3>
                <p>
                  <a href="https://www.youtube.com/" target="_blank">YouTube</a><br>
                  <a href="https://www.facebook.com/" target="_blank">Facebook</a><br>
                  <a href="https://twitter.com/" target="_blank">Twitter</a>
                </p>
              </div>
            </div>
          </div>


          <!-- Copyright & Developer Info -->
          <!-- links to my github and blog -->

          <div class="row bg-info text-white text-center">
            <div class="col-sm-12">
              <small>&copy; 2018 <span>AAM Event Tast Manager. All Rights Reserved.</span> Developed by <a class="text-white" href="http://adeelstechbeat.net/">Mohammad Adeel</a> | <a class="text-white" href="https://github.com/AAM77/hearth_and_home_inventory">GitHub</a></small>
            </div>
          </div>

        </div> <!-- yield / main-content container -->
        </div>
      </div>  <!-- container-fluid background -->



  </body>
</html>